ALTER TABLE IF EXISTS projects ADD COLUMN IF NOT EXISTS latency_profile VARCHAR(255) DEFAULT 'NONE';
ALTER TABLE IF EXISTS projects ADD COLUMN IF NOT EXISTS global_latency_ms INTEGER DEFAULT 0;
ALTER TABLE IF EXISTS projects ADD COLUMN IF NOT EXISTS jitter_ms INTEGER DEFAULT 0;
ALTER TABLE IF EXISTS endpoints ADD COLUMN IF NOT EXISTS is_template BOOLEAN DEFAULT FALSE;
ALTER TABLE IF EXISTS endpoints ADD COLUMN IF NOT EXISTS active_variant_id UUID;
